name: Luz
api: [5.0.0] 
main: Luz\Main
author: Luriuker 
version: 2.0.0
commands:
  luz:
    description: on|off
    use: "/luz <on|off>"
    permission: luz.cmd

permissions:
  luz.cmd:
    description: Permissão para usa o /luz
    default: true
