name: Luz
api: [3.0.0, 3.12.2, 3.13.0, 3.14.2, 4.0.0] 
main: Luz\Luz
author: Luriuker 
version: 2.0.0
commands:
  luz:
    description: on|off
    use: "/luz <on|off>"
    permission: luz.cmd

permissions:
  luz.cmd:
    description: Permissão para usa o /luz
    default: true
