name: Luz
api: [5.0.0] 
main: Luz\Main
author: Lu-a-png 
version: 3
commands:
  ligth:
    description: on|off
    use: "/ligth <on|off>"
    permission: ligth.cmd

permissions:
  ligth.cmd:
    description: Permissão para usa o /ligth
    default: true
