name: Luz
api: [5.0.0]
main: Luz\Main
author: Lu-a-png
version: 3.6
commands:
  light:
    description: auto|on|off
    permission: light.use

permissions:
  light.use:
    description: Permission to use /light
    default: true